import { ReactNode } from 'react';
import Link from 'next/link';

import './global.css';

export const metadata = {
  title: 'Welcome to landings',
  description: 'Generated by create-nx-workspace',
};

type RootLayoutProps = {
  children: ReactNode;
};

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en">
      <body className="text-zinc-950 min-h-screen flex flex-col">
        <div className="sticky top-0 inset-x-0 bg-white/60 backdrop-blur flex-shrink-0">
          <div className="container max-w-screen-2xl mx-auto flex items-center h-14 gap-4 px-8">
            <Link href="/">
              <span className="font-bold">bearrr</span>
            </Link>
            <nav className="flex items-center gap-4 text-sm">
              <a className="text-zinc-950/60 hover:text-zinc-950/80">Blog</a>
              <a className="text-zinc-950/60 hover:text-zinc-950/80">Updates</a>
              <a className="text-zinc-950/60 hover:text-zinc-950/80">
                Download
              </a>
              <a
                className="text-zinc-950/60 hover:text-zinc-950/80"
                href="https://github.com/indy-dough/todo"
                target="_blank"
              >
                GitHub
              </a>
            </nav>
            <div className="flex-grow flex-shrink flex items-center justify-end gap-4">
              <nav className="flex items-center gap-4 text-sm">
                <Link
                  className="text-zinc-950/60 hover:text-zinc-950/80"
                  href="/sign-in"
                >
                  Sign in
                </Link>
              </nav>
            </div>
          </div>
        </div>
        {children}
      </body>
    </html>
  );
}
